/**
 *
 * Issue/Проблема: https://leetcode.com/problems/find-the-difference/
 * 
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * Даны две строки s и t. Строка t образованна путем перемешивания символов строки s с прибавлением одного символа, 
 * которого нет в строке s. Найдите и верните этот  символ.
 * 
 * Constraints/Ограничения:
 * 
 * - 0 <= s.length <= 1000
 * - t.length == s.length + 1
 * - s and t consist of lowercase English letters.
 * 
 * Score solution/Оценка решения:
 * Runtime beats 44,12% O(logN) 
 * Memory beats 16,91% O(N)
 * 
 * Telegram:  https://t.me/c/2225351477/107
 */
class Solution {
    fun findTheDifference(s: String, t: String): Char {
        val sArray = s.toCharArray().sortedArray()
        val tArray = t.toCharArray().sortedArray()

        for(index in 0..sArray.size-1) {
            if(sArray[index] != tArray[index]) return tArray[index]
        }

        return tArray[tArray.size-1]
    }
}